#include "efigvars.h"

EFI_SYSTEM_TABLE* ST;
EFI_BOOT_SERVICES* BS;
EFI_RUNTIME_SERVICES* RT;

EFI_GUID LoadedImageProtocolGuid = EFI_LOADED_IMAGE_PROTOCOL_GUID;
EFI_GUID DevicePathProtocolGuid = EFI_DEVICE_PATH_PROTOCOL_GUID;
EFI_GUID DevicePathToTextProtocolGuid = EFI_DEVICE_PATH_TO_TEXT_PROTOCOL_GUID;
EFI_GUID DevicePathFromTextProtocolGuid = EFI_DEVICE_PATH_FROM_TEXT_PROTOCOL_GUID;
EFI_GUID DevicePathUtilitiesProtocolGuid = EFI_DEVICE_PATH_UTILITIES_PROTOCOL_GUID;
EFI_GUID DiskIoProtocolGuid = EFI_DISK_IO_PROTOCOL_GUID;
EFI_GUID DiskIo2ProtocolGuid = EFI_DISK_IO2_PROTOCOL_GUID;
EFI_GUID BlockIoProtocolGuid = EFI_BLOCK_IO_PROTOCOL_GUID;
EFI_GUID BlockIo2ProtocolGuid = EFI_BLOCK_IO2_PROTOCOL_GUID;

EFI_LOADED_IMAGE_PROTOCOL* LoadedImageProtocol = NULL;
EFI_DEVICE_PATH_TO_TEXT_PROTOCOL* DevicePathToTextProtocol = NULL;
EFI_DEVICE_PATH_FROM_TEXT_PROTOCOL* DevicePathFromTextProtocol = NULL;
EFI_DEVICE_PATH_UTILITIES_PROTOCOL* DevicePathUtilitiesProtocol = NULL;
EFI_DISK_IO_PROTOCOL* DiskIoProtocol = NULL;
EFI_BLOCK_IO_PROTOCOL* BlockIoProtocol = NULL;
